project_id = "uyyeopwcrrvvlwcmmxux"

[functions.chat]
verify_jwt = true

[functions.voice-to-text]
verify_jwt = true

[functions.text-to-speech]
verify_jwt = true

[functions.process-document]
verify_jwt = true